import uuid
from sqlalchemy import Column, String, Text, DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from db.database import Base


class HrJob(Base):
    """
    Represents a Job Description posted by HR.
    
    Table name: hr_jobs
    
    Why UUID for primary key instead of Integer?
    - UUID is globally unique — no collisions if we ever shard the DB
    - Integer IDs are predictable (1, 2, 3...) — security risk
    - UUID looks like: "550e8400-e29b-41d4-a716-446655440000"
    
    Why unique_slug separate from id?
    - id (UUID) is internal — DB foreign keys, joins etc.
    - unique_slug is external — what we show in the URL
    - Separation of concerns: internal ID vs public-facing token
    """

    __tablename__ = "hr_jobs"

    # Primary Key — UUID generated by Python (not DB) for consistency
    id = Column(
        UUID(as_uuid=True),          # PostgreSQL UUID type
        primary_key=True,
        default=uuid.uuid4,          # Auto-generate on creation
        index=True,
    )

    # unique=True → DB enforces no duplicates
    # index=True  → fast lookups by slug (we'll query this a LOT)
    unique_slug = Column(String(20), unique=True, nullable=False, index=True)

    # Job details
    title = Column(String(255), nullable=False)

    # Text — for long strings (no length limit, unlike String)
    # nullable=True → HR might only upload PDF, not type text
    description = Column(Text, nullable=True)

    # Supabase Storage URLs for uploaded files
    jd_pdf_url = Column(String(500), nullable=True)
    jd_image_url = Column(String(500), nullable=True)

    # LLM-extracted clean text from PDF/Image
    # This is what we send to the LLM for scoring
    jd_extracted = Column(Text, nullable=True)

    # "active" = accepting applications, "closed" = not accepting
    status = Column(String(20), nullable=False, default="active")

    # Timestamps — server_default means PostgreSQL sets this, not Python
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # ── ORM Relationship ─────────────────────────────────────────────────────
    # This lets us do: job.applications → get all JobApplication objects for this job
    # back_populates="job" must match JobApplication.job attribute name
    applications = relationship(
        "JobApplication",
        back_populates="job",
        cascade="all, delete-orphan",  # delete applications when job is deleted
    )